config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get '/orders/new_order', to: 'orders#new', as: 'orders_new'
  resources :orders
  devise_for :admins
  root 'home#index'

  namespace :admins do
    resources :products
    namespace :products do
      post 'csv_upload'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categories_product.rb
class CategoriesProduct < ApplicationRecord
    belongs_to :category
    belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :categories_products
    has_many :products, through: :categories_products
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
    enum status: [:draft, :published, :archived]

    scope :search, -> (arg) {where("title LIKE ? or description LIKE ?", "%#{arg}%", "%#{arg}%")}

    validates :stock, numericality: {greater_than_or_equal_to: 0}
    validates :title, length: { minimum: 1 }
    validates :description, length: { minimum: 1 }

    has_many :categories_products
    has_many :categories, through: :categories_products
    has_one_attached :primary_image
    has_many_attached :supporting_images

    attr_accessor :remove_primary_image, :remove_supporting_images

    after_save :purge_primary_image, if: :remove_primary_image
    private def purge_primary_image
        return unless @remove_primary_image == '1'
        primary_image.purge_later
    end

    after_save :purge_supporting_images, if: :remove_supporting_images
    private def purge_supporting_images
        return unless @remove_supporting_images == '1'
        supporting_images.purge_later
    end
end

app/controllers/admins/products_controller.rb
module Admins
  class ProductsController < ApplicationController
    before_action :set_product, only: %i[ show edit update destroy ]
    before_action :authenticate_admin!, except: [ :show, :index]

    # GET /products or /products.json
    def index
      @search = params[:search]

      @products = Product.all
      @products = @products
        .search(@search) if @search.present?
      @products = @products.page(params[:page]).per(5)

      respond_to do |format|
        format.html
        format.csv{ send_data generate_csv(Product.all), file_name: 'products.csv' }
      end
    end

    # GET /products/1 or /products/1.json
    def show
    end

    # GET /products/new
    def new
      @product = Product.new
    end

    # GET /products/1/edit
    def edit
    end

    # POST /products or /products.json
    def create
      @product = Product.new(product_params)

      respond_to do |format|
        if @product.save
          format.html { redirect_to admins_product_path(@product), notice: "Product was successfully created." }
          format.json { render :show, status: :created, location: admins_product_path(@product) }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /products/1 or /products/1.json
    def update
      respond_to do |format|
        if @product.update(product_params)
          format.html { redirect_to admins_product_path(@product), notice: "Product was successfully updated." }
          format.json { render :show, status: :ok, location: admins_product_path(@product) }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /products/1 or /products/1.json
    def destroy
      @product.destroy
      respond_to do |format|
        format.html { redirect_to admins_products_path, notice: "Product was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    def csv_upload
      data = params[:csv_file].read.split("\n")
      data.each do |line|
        attr = line.split(",").map(&:strip)
        Product.create title: attr[0], description: attr[1], stock: attr[2]
      end
      redirect_to admins_products_path
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_product
        @product = Product.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def product_params
        params.require(:product).permit(:title, :description, :stock, :status, :primary_image, :remove_primary_image, :remove_supporting_images, :supporting_images=>[], :category_ids=>[])
      end

      def generate_csv(products)
        products.map do |a|
          [a.title, a.description].join(',')
        end.join("\n")
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_categories

    private
 
    def set_categories
        @categories = Category.all
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, except: [:index, :show]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @search = params[:search]

    @products = Product.all
    @products = @products
      .search(@search) if @search.present?
    @products = @products.page(params[:page]).per(8)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :authenticate_admin!, only: [:index]
    def index
        @orders = Order.all
    end

    def show
        @order = Order.find(params[:id])
        @product = Product.find(@order.product_id)
    end
    
    def new
        @order = Order.new
        @product = Product.find(params[:id].to_i)
        @product_id = params[:id].to_i
    end

    def create
        @order = Order.new(order_params)

        if @order.save
            redirect_to @order
        else
            render :new
        end
    end

    private
        def order_params
            params.require(:order).permit(:product_id, :address)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admins/products/_form.html.erb
<%= form_with(model: [:admins, product]) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <br>
  <div class= "field.form-group">
    <%= form.label :primary_image %>
    <p>
    <% if @product.primary_image.attached? %>
      <%= image_tag @product.primary_image %>
      <br>
      <%= form.check_box :remove_primary_image %>
      <%= form.label "Delete image?" %>
    <%end%>
    </p>
    <%= form.file_field :primary_image, class:"form-control" %>
  </div>

  <br>
  <div class= "field.form-group">
    <%= form.label :title %>
    <%= form.text_area :title, class:"form-control" %>
  </div>

  <br>
  <div class= "field.form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class:"form-control" %>
  </div>

  <br>
  <div class= "field.form-group">
    <%= form.label :stock %>
    <%= form.number_field :stock, class:"form-control" %>
  </div>

  <br>
  <div class = "field.form-group"> 
    <%= form.label :Categories %>
    <br>
    <%= form.collection_check_boxes :category_ids, Category.order(:name), :id, :name, class:"mr-10" %>
  </div>

  <div class = "field.form-group"> 
    <%= form.label :Status %>
    <br>
    <%= form.select :status, Product.statuses.keys.map {|u| [u.titleize, u]} %>
  </div>
  <br>
  <div class= "field.form-group">
    <%= form.label :supporting_images %>
    <p>
      <% if @product.supporting_images.attached? %>
        <% @product.supporting_images.each do |image| %>
          <%= image_tag image, width: "100px", height: "100px" %>
        <% end %>
        <br>
        <%= form.check_box :remove_supporting_images %>
        <%= form.label "Delete images?" %>
      <%end%>
    </p>
    <%= form.file_field :supporting_images, multiple: true ,class:"form-control" %>
  </div>


  <br>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', admins_product_path(@product) %> |
<%= link_to 'Back', admins_products_path %>

app/views/admins/products/index.slim
.row
  .col-6
    h1 Products List


.row
  .col
    = form_tag admins_products_path, method: :get do
     = text_field_tag 'search', @search, placeholder: 'Type something here',
      class: 'form-control'
  - if admin_signed_in?
    .col-2
      = link_to admins_products_path(format: :csv) do
        = button_tag 'Download CSV', class: 'btn btn-secondary float-right'

.row.mt-2
  .col
    table.table.table-bordered.table-striped.table-hover
      thead.thead-dark
        tr
          th ID
          th Image
          th Status
          th Title
          th Description
          th Stock
          th Supporting images
          th Action
      tbody
        - @products.each do |pr|
          tr.hoverable-row
            td = pr.id
            td
              - if pr.primary_image.attached?
                = image_tag pr.primary_image, width: "50px", height: "50px"
            td = pr.status
            td.font-weight-bold = pr.title
            td = pr.description
            td = pr.stock
            td
              - if pr.supporting_images.attached?
                - pr.supporting_images.each do |image|
                  = image_tag image, width: "50px", height: "50px"
            td
              span 
                = link_to admins_product_path(pr) do
                  i.fas.fa-eye
              - if admin_signed_in?
                span.ml-3
                  = link_to edit_admins_product_path(pr) do
                    i.fas.fa-pen
                span.ml-3
                  = link_to admins_product_path(pr), method: :delete, data: {confirm: "Are you sure?"} do
                    i.fas.fa-trash

.row
  .col-6
      = paginate @products
  .col-6
    .float-right
      = link_to new_admins_product_path do 
        = button_tag 'Add New Product', class: 'btn btn-primary'

- if admin_signed_in?
  div
    hr

  h3 Add products with csv file
  .row
    .col
      = form_tag admins_products_csv_upload_path, multipart: true do
        div = file_field_tag :csv_file
        div = submit_tag :upload

  

app/views/admins/products/index_old.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.stock %></td>
        <td><%= link_to 'Show', admins_product_path(product) %></td>
        <td><%= link_to 'Edit', edit_admins_product_path(product) %></td>
        <td><%= link_to 'Destroy', admins_product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_admins_product_path %>

app/views/admins/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', admins_products_path %>

app/views/admins/products/show.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">

    <% if @product.primary_image.attached? %>
      <%= image_tag @product.primary_image %>
    <%end%>
    <h1>
      <%= @product.title %>
    </h1>
    <p>
      <strong>Description:</strong>
      <%= @product.description %>
    </p>
    <p>
      <strong>Stock:</strong>
      <%= @product.stock %>
    </p>
    <p>
      <strong>Status:</strong>
      <%= @product.status %>
    </p>

    <p>
      <strong>Category:</strong>
      <% @product.categories.each do |category| %>
        <span href="#" class="badge badge-primary"><%= category.name %></span>
      <% end %>
    </p>

    <p>
      <strong>Supporting images:</strong>
      <% if @product.supporting_images.attached? %>
        <% @product.supporting_images.each do |image| %>
          <%= image_tag image, width: "100px", height: "100px" %>
        <% end %>
      <%end%>
    </p>

    <%= link_to 'Edit', edit_admins_product_path(@product) %> |
    <%= link_to 'Back', admins_products_path %>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Products:</strong>
  <% @category.products.each do |product| %>
    <%= link_to admins_product_path(product) do %>
      <span class="badge badge-dark">
      <%= product.title %> 
      </span>
    <% end %>
  <% end %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/index.html.erb
<form action=/ method="get">
  <input id = @search  name= search placeholder= 'Type something here' class= 'form-control' />
</form>

<div class='container-fluid'>
  <div class="row justify-content-md-center">
    <% @products.each do |pr| %>
        <div class="grid-item col-6 col-md-4 col-lg-3 mt-4 mb-3"> 
        <% if pr.primary_image.attached? %>
          <%= image_tag(pr.primary_image, height: '200px', width: '200px', class: 'rounded mx-auto d-block') %>
        <% end %>
        <div class="card-body text-center mx-auto">
          <div class='cvp'>
            <h5 class="card-title font-weight-bold"> <%= pr.title %> </h5>
            <p class="card-text">$299(PlaceHolder)</p> 
            <%= link_to 'View details', admins_product_path(pr), class: "btn details px-auto" %>
            <br /> 
            <%= link_to 'Buy now!', orders_new_path(:id => pr.id), class: "btn cart px-auto" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= paginate @products %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Suprun</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css'%>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #FF0000; font-family: Helvetica, Arial, sans-serif; 
  font-weight: bold; ">
      <a class="navbar-brand" href="/" style="color:white; font-size: 30px" >Suprun</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/admins/products" style="color:white">Products</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color:white">
              Category
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% @categories.each do |category| %>
                <%= link_to category do %>
                  <span class="dropdown-item">
                  <%= category.name %> 
                  </span>
                <% end %>
              <% end %>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="/categories">Show all</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/orders" style="color:white">Orders</a>
          </li>
          <% if admin_signed_in? %>
            <li class="nav-item">
              <a class="nav-link" href="/admins/edit" style="color:white">Edit Profile</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/admins/sign_out" data-method= "DELETE" style="color:white">Sign Out</a>
            </li>
          <% else %>
            <li class="nav-item">
              <a class="nav-link" href="/admins/sign_in" style="color:white">Sign In</a>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="container">
      <h1 style="color: red;">
        <%= flash[:error]&.join(',') %>
      </h1>
      <%= yield %>

      <%= javascript_include_tag 'https://code.jquery.com/jquery-3.2.1.slim.min.js'%>
      <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js'%>
      <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js'%>
    </div>
  </body>
</html>

app/views/orders/index.slim
h1 Order List
- @orders.each do |order|
  .row.mt-2
    .col
      .card
        .card-body
          .row
            .col-3
              - if Product.find(order.product_id).primary_image.attached?
                = image_tag  Product.find(order.product_id).primary_image, width: '100%'
            .col-9
              .row
                .col
                  h1 =  Product.find(order.product_id).title
              .row
                .col
                  =  "address: #{order.address}"
              .row
                .col
                  = link_to order_path(order.id) do
                    = button_tag 'View order', class: 'btn btn-dark btn-sm mr-1 mb-2'

app/views/orders/new.html.erb
<h1> New Order </h1>
<p>
    Placing an order on: <%= @product.title %>
</p>
<%= form_with model: @order do |form| %>
    <div>
        <%= form.hidden_field :product_id, value: @product_id %>
    </div>

    <div class="field form-group">
        <%= form.label :address %><br>
        <%= form.text_area :address, class:"form-control"%>
    </div>

    <div class="actions">
        <%= form.submit class:"btn btn-secondary"%>
    </div>
<% end %>

<br>
<%= link_to root_path do %>
    <% button_tag 'Back', class: 'btn btn-dark btn-sm mr-1 mb-2' %>
<% end %>

app/views/orders/show.slim
h2 = "Product name: #{@product.title}"
- if @product.primary_image.attached?
    = image_tag @product.primary_image, width: '100%'
h3 = "Address: #{@order.address}"

= link_to root_path do 
    = button_tag 'Back', class: 'btn btn-dark btn-sm mr-1 mb-2'

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.stock %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', root_path %>

app/views/products/show.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1>
      <%= @product.title %>
    </h1>
    <p>
      <strong>Description:</strong>
      <%= @product.description %>
    </p>
    <p>
      <strong>Stock:</strong>
      <%= @product.stock %>
    </p>
    <p>
      <strong>Status:</strong>
      <%= @product.status %>
    </p>

    <p>
      <strong>Category:</strong>
      <% @product.categories.each do |category| %>
        <span href="#" class="badge badge-primary"><%= category.name %></span>
      <% end %>
    </p>
    <%= link_to 'Edit', edit_product_path(@product) %> |
    <%= link_to 'Back', root_path %>
  </div>
</div>